version: '3'
services:
  postgres_ip:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: simplepass
      POSTGRES_USER: dozer
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  lavalink:
    image: fredboat/lavalink:master-v3
    environment:
      LAVALINK_SERVER_PASSWORD: youshallnotpass
      SERVER_PORT: 2333
      SERVER_HOST: 127.0.0.1
  dozer:
    depends_on: 
      - postgres_ip
      - lavalink
    build: .
    volumes:
      - ".:/app"
      
volumes:
  database:
